[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.watch-build]
command = "cargo"
args = ["watch", "--", "cargo", "run"]

[tasks.watch-test]
command = "cargo"
args = ["watch", "--", "cargo", "nextest", "run"]

[tasks.watch]
run_task = { name = ["watch-build", "watch-test"], parallel = true }
